version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: toor

  order-db:
    image: postgres:latest
    container_name: order-db
    environment:
      POSTGRES_USER: order_user
      POSTGRES_PASSWORD: order_password
      POSTGRES_DB: order_db
    volumes:
      - order-invoice-postgres-order-data:/var/lib/postgresql/data

  invoice-db:
    image: postgres:latest
    container_name: invoice-db
    environment:
      POSTGRES_USER: invoice_user
      POSTGRES_PASSWORD: invoice_password
      POSTGRES_DB: invoice_db
    volumes:
      - order-invoice-postgres-invoice-data:/var/lib/postgresql/data

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    image: order-service:latest
    ports:
      - "3001:3000"
    depends_on:
      - order-db
      - rabbitmq
    container_name: order-service
    environment:
      AMQP_URL: ${AMQP_URL}
      DATABASE_URL: ${ORDER_DATABASE_URL}
      INVOICE_SERVICE_URL: ${INVOICE_SERVICE_URL}
      PORT: ${ORDER_SERVICE_PORT}

  invoice-service:
    build:
      context: ./invoice-service
      dockerfile: Dockerfile
    image: invoice-service:latest
    ports:
      - "3002:3000"
    depends_on:
      - invoice-db
      - rabbitmq
    container_name: invoice-service
    environment:
      AMQP_URL: ${AMQP_URL}
      DATABASE_URL: ${INVOICE_DATABASE_URL}
      ORDER_SERVICE_URL: ${ORDER_SERVICE_URL}
      PORT: ${INVOICE_SERVICE_PORT}

volumes:
  order-invoice-postgres-order-data:
  order-invoice-postgres-invoice-data:
